### ISSUE TITLE
Layout bug for specific markdown

### ISSUE THREAD

**Issue by rootext** [gera2ld/markmap-lib#1]
```
# dddd

## fruits
- fff

## ffff
- banana
- dddd
- mango
- melon
- orange

# fff
- f
```
Hi, the following markdown has buggy layout.

**Comment by thomaskoppelaar** [comment]
To provide a bit more context: 
![image](https://user-images.githubusercontent.com/36331365/79047526-5deb1180-7c17-11ea-8a64-331da49976a9.png)
