### ISSUE TITLE
Passing the markdown file to transform method.

### ISSUE THREAD

**Issue by joshikeerti** [gera2ld/markmap-lib#13]
Hi,

I am trying to use Markmap in a browser app. If I have a .md file, is it possible to pass the file to the transform or does the file need to be parsed and then passed as a string to the transform?

import { transform } from 'markmap-lib/dist/transform.common';
const data = transform(markdown);

**Comment by gera2ld** [comment]
I'm not sure what you mean by `the file need to be parsed and then passed as a string`.
`transform` accepts a string, which is the content of your Markdown. So if you have a .md file, you'll need to read its content and pass to `transform`.
