### ISSUE TITLE
Collapsed map flag

### ISSUE THREAD

**Issue by automateyournetwork** [gera2ld/markmap-lib#14]
Hello! 

I love this tool! 

Is there anyway to add a flag at runtime to render the map with all the branches collapsed by default? My maps launch with all branches expanded and they are rather large - is there anyway to flag --collapsed or something so the map starts with only root and all branches collapsed by default?

**Comment by gera2ld** [comment]
There is no way to set this flag in Markdown ATM.
Nevertheless there is a flag used internally: `node.p.f = true`, where `f` stands for `folded`.

It will be great if we can use some friendly syntax to mark a node as folded in the Markdown.

**Comment by automateyournetwork** [comment]
Thank you for the quick response! I understand now it would be a flag in the markdown that the map would use to fold the branch. Thanks again.
