### ISSUE TITLE
YAML instead of Markdown

### ISSUE THREAD

**Issue by lucianmarin** [gera2ld/markmap-lib#2]
YAML can be more useful than Markdown for mindmaps.

**Comment by thomaskoppelaar** [comment]
How so? Could you provide more context?

**Comment by gera2ld** [comment]
I think YAML (or JSON) can only describe the structure of the generated mindmaps, as some internal data structure.
It's less readable and contains less information than Markdown. What's more, Markdown supports inline styles out of the box but YAML is not good at that.
