### ISSUE TITLE
The ⤧ symbol is unclear

### ISSUE THREAD

**Issue by borekb** [gera2ld/markmap-lib#20]
<img width="969" alt="Screenshot 2020-05-06 at 21 02 43" src="https://user-images.githubusercontent.com/101152/81217494-fd17e480-8fdc-11ea-88da-41ffdd11cf7b.png">

I was expecting this button to expand the canvas to the full screen and thought it's buggy. Only later I realized that it means "reset the zoom to 1:1". Maybe some different symbol could be used, like that magnifying glass with a plus/minus in it?

**Comment by gera2ld** [comment]
Fixed in the latest version: 
![image](https://user-images.githubusercontent.com/3139113/81489569-8400e180-92a9-11ea-9be2-fb725e0c4cc9.png)

**Comment by borekb** [comment]
Nice, thank you!
