### ISSUE TITLE
Error "Uncaught (in promise)" when loading prismJS plugin

### ISSUE THREAD

**Issue by ChiaraDipi** [gera2ld/markmap-lib#23]
Hi,
I've included your awesome lib inside an Angular 9 application. 
When I load prismJS plugin as indicated in the API documentation, I get the following error:
```
ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (zone-evergreen.js:798)
    at SVGSVGElement.<anonymous> (zone-evergreen.js:705)
    at Dispatch.call (dispatch.js:57)
    at start (schedule.js:88)
    at schedule (schedule.js:66)
    at timerFlush (timer.js:61)
    at wake (timer.js:71)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41344)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
``` 
Despite this, the map and the plugin work perfectly, but I wonder if there is a way to avoid this error message in the console.

**Comment by gera2ld** [comment]
The error stack seems to have nothing to do with this library. Can you figure out which line is causing this? It would be great if you can provide a minimal reproduction for it.

**Comment by ChiaraDipi** [comment]
In the console I've the following warnings before the error:
<img width="1108" alt="Schermata 2020-05-20 alle 11 58 06" src="https://user-images.githubusercontent.com/7116412/82433205-698cec00-9a91-11ea-8f17-8e828f6ad1b2.png">

Everything refers to `zone-evergreen.js`, so it's probably a problem with my app, which is quite complex and I don't know how to help you reproduce it.
If it is any help I've noticed that it only appears when I use 
```
loadPlugins([
   'prism',
]).then(() => {
   Markmap.create(mapElement, null, mapData);
});
```

And disappear if I disable entering animation by using `   Markmap.create(mapElement, { duration: 0 }, mapData);`. For my purpose I can go without animation.
