### ISSUE TITLE
User-customizable option to specify depth?

### ISSUE THREAD

**Issue by sundarvenkata-EBI** [gera2ld/markmap-lib#25]
Currently I only see 5 or 6 levels of depth rendered. Is it possible to make this customizable?

**Comment by gera2ld** [comment]
What do you mean by "depth"? I don't see any limit on this.

**Comment by sundarvenkata-EBI** [comment]
If the markdown has 10 levels of indentation, I only see up to Level 6 rendered...

# Level 1
## Level 2
### Level 3
#### Level 4
##### Level 5
###### Level 6
####### Level 7
######## Level 8

**Comment by sundarvenkata-EBI** [comment]
Ok. My bad... I was using the # for indentation when I should have used the * indentation.

**Comment by gera2ld** [comment]
`#` in Markdown represents headings, there are only `h1` ~ `h6` in HTML, so more `#`s won't work.
