### ISSUE TITLE
**bold text** is broken

### ISSUE THREAD

**Issue by Nuc1eoN** [gera2ld/markmap-lib#27]
The bold text styling using `**bold**` is not working.

The bold font weight is being overwritten with `font-weight: 500` by a different class in the css somewhere.

**Comment by gera2ld** [comment]
This is intended. Do you expect `font-weight: bold` instead of `font-weight: 500`?

**Comment by Nuc1eoN** [comment]
Well I would expect the text to be **bold** when doing `**bold**`, I dont really understand the question.

**Comment by gera2ld** [comment]
The text is bold, just that the weights differ.

Generally `font-weight: bold` is the same as `font-weight: 700`. But modern fonts look better when thinner, especially in Mac OS / iOS. So we usually use `600` or `500` for bold text instead of `bold` / `700`.

By the way, the **bold text here** in GitHub has `font-weight: 600` rather than `bold`.

**Comment by Nuc1eoN** [comment]
Ok but for me the text is *not* bold.
![image](https://user-images.githubusercontent.com/2538022/84413905-8b513d00-ac11-11ea-8e2c-fb414e26cc07.png)
The word "inline" should be bold, correct?
It looks exactly the same as the other words.

**Comment by Nuc1eoN** [comment]
To avoid any further misunderstandings:
![image](https://user-images.githubusercontent.com/2538022/84415290-d881de80-ac12-11ea-9560-1a7d82b5905d.png)
The bold text is not bold...

**Comment by gera2ld** [comment]
Maybe your font does not work well with number font-weights. I think I'll change the default `font-weight` to `600` later, as in GitHub. It works for me though.
<img width="200" alt="Screen Shot 2020-06-12 at 10 23 09" src="https://user-images.githubusercontent.com/3139113/84458063-bfbb0c80-ac96-11ea-8ede-5bb65f430596.png">

**Comment by Nuc1eoN** [comment]
Yeah I played around with it and it appears my font doesn't get bold at `font-weight: 500` but only at `600`.
I switched my font to a different one now, but for first time user it might be confusing.

You could also specify to use a certain default font alternatively, which would require pulling from cdn probably to make it universal for all.
Or just use `600`.
