### ISSUE TITLE
Add a howto start the markmap-lib in the browser

### ISSUE THREAD

**Issue by futchas** [gera2ld/markmap-lib#29]
I can't figure out how to get markmap running locally in the browser. So I have something like https://markmap.js.org/repl on my machine. The project you got inspired from an instruction with examples are available: https://github.com/dundalek/markmap#browser
Can you add something like this, please?

**Comment by gera2ld** [comment]
See command-line usage: https://github.com/gera2ld/markmap-lib#command-line
It will build an HTML for you based on a Markdown file and open it in your browser.

```sh
$ npx markmap-lib markdown-file.md
```

Please let me know if you think the usage section is confusing.

**Comment by futchas** [comment]
I tried the comman-line tool running `markmap README.md` but the generated html doesn't load and is corrupt (multiple html and body tags and sequence of special characters
![image](https://user-images.githubusercontent.com/1629275/85259343-2e535380-b469-11ea-9a9a-c74003773d4a.png)

Also I wanna try to use it without the command-line and the API section is indeed confusing. I'm a backend dev and doesn't have much frontend experience.  It seems you are using TypeScript, right? I tried to use `npm run dev` which seems to watch file changes but not sure how the workflow is to further develop. Mainly I'd like to have a markdown section on the left and a mindmap on the right. On each side I wanna be able to update/sync the text to the other side. So pretty similar to your current demo, but it does only support updating the mindmap when the markdown is changes. I'd like to extend it to be able to change the text on the right

**Comment by gera2ld** [comment]
> (multiple html and body tags and a weird sequence of special characters)

Something must be wrong here. It would be great if you can provide steps to get this.

> On each side I wanna be able to update/sync the text to the other side.

This is a good idea similar to #28 but not implemented yet.

> I tried to use `npm run dev` which seems to watch file changes but not sure how the workflow is to further develop.

There is no such workflow here. The website / demo is another project with much extra work, like the UI thing. This project only provides the core functions, to extract nodes from Markdown, and render the nodes to a graph.

**Comment by futchas** [comment]
> Something must be wrong here. It would be great if you can provide steps to get this.
Just followed your instruction
```
yarn global add markmap-lib
markmap README.md
```
Then I opened the generated `README.html` with my IDE and saw how broken the syntax is. Opening the html file in the browser resulted in not loading and errors thrown.

> There is no such workflow here. The website / demo is another project with much extra work, like the UI thing. This project only provides the core functions, to extract nodes from Markdown, and render the nodes to a graph.
Why not open source the website/demo too? That would be very useful. Otherwise I have to go back to the markmap which is not as up-to-date and maintained as yours

**Comment by futchas** [comment]
I'd appreciate an answer

**Comment by gera2ld** [comment]
> Why not open source the website/demo too?

Because this project is just a library to create a graph from a Markdown, which is supposed to be simple enough to be used in other projects. And it is AFAIK.

The demo website is just a personal website that uses this library to demonstrate that it works. I don't see any necessity to open source it. I think it's better to integrate such a demo into the CLI.

**Comment by pintergreg** [comment]
Sorry if I'm not posting this into a closed thread.

I want to turn a part of my page into a Mindmap, but using markdown instead of a precompiled JSON, so I came up with this snippet:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

    <body>
        <svg id="mindmap"></svg>
        <script src="https://cdn.jsdelivr.net/npm/d3@5"></script>
        <script src="https://cdn.jsdelivr.net/npm/markmap-lib@0.7.11/dist/browser/view.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/markmap-lib@0.7.11/dist/browser/transform.min.js"></script>

        <pre id="mm" hidden>
# foobar

## foo

- f
- o
- o

## bar

- b
- a
- r
        </pre>
        <script>
            markdown =  document.getElementById("mm").innerHTML;
            const data = markmap.transform(markdown);

            markmap.Markmap.create("#mindmap", null, data);
        </script>
    </body>

</html>
```
The drawback is obviously that the markdown code should start at column 0, but this will do its part for now.
