### ISSUE TITLE
zoom svg and download html ?

### ISSUE THREAD

**Issue by mifunc** [gera2ld/markmap-lib#31]
I introduced the library you wrote through the script tag, I have not written TS code, to get your help, thank you.

1. Which function is brain image zoom in and zoom out, and how to call it in the browser?

2. Which function to download the HTML and how to call it in the browser?

**Comment by mifunc** [comment]
![image](https://user-images.githubusercontent.com/14819748/86511008-a9344b00-be27-11ea-8117-d605d64c45c0.png)

**Comment by gera2ld** [comment]
```js
const mm = Markmap.create(...);

// fit the size of container
mm.fit();

// change size
mm.rescale(1.25); // 5/4 larger
mm.rescale(0.8); // 4/5 smaller
```

I think the documentation needs to be updated someday.
