### ISSUE TITLE
feature request: option to render markdown file in the background

### ISSUE THREAD

**Issue by CyrusYip** [gera2ld/markmap-lib#33]
Hello, @gera2ld . Could you add options to keep markmap-lib rendering markdown file in the background?

When I write a markdown document and use markmap-lib to render it, I need to execute `markmap myfile.md` regularly to refresh the mindmap. It is kind of inconvenient.

I hope there will be option like `--keep` to keep markmap-lib running in the background to refresh the file. After using markmap-lib, use `--quit` to stop markmap-lib running in the background. It would be better if markmap can automatically quit after I close the html file and markdown file.

**Comment by gera2ld** [comment]
So you possibly mean hot-reload?

**Comment by CyrusYip** [comment]
> So you possibly mean hot-reload?

Yes, you are right.

**Comment by gera2ld** [comment]
It's supported in v0.7.12 now:

```sh
$ markmap -w note.md
```
