### ISSUE TITLE
It seems that wrong <em> tags occurs when converting files

### ISSUE THREAD

**Issue by YM-MA** [gera2ld/markmap-lib#35]
I was working with inline math formulas. It seems that when dealing with formulas whose 'd' is high, the em tag might untimely occurs, causing a chaos in the following few lines.
<img width="914" alt="Annotation 2020-08-05 223117" src="https://user-images.githubusercontent.com/49449845/89425348-773a3f80-d76b-11ea-9198-f2663867bed1.png">
 
my note and generated html are here:
[https://ym-ma.github.io/markdown.md](url)
[https://ym-ma.github.io/markdown.html](url)

I inserted codes into the generated html file to enalbe inline math:
`<script src="https://ym-notes.oss-cn-beijing.aliyuncs.com/img/load-mathjax.js" async></script>`

**Comment by gera2ld** [comment]
You need to escape `_`s in Markdown.
See also https://github.com/gera2ld/markmap-lib/issues/9#issuecomment-617031900
