### ISSUE TITLE
Can I get the svg without query slector?

### ISSUE THREAD

**Issue by dodok8** [gera2ld/markmap-lib#8]
I just want to get stirng data of `<svg>` tag, result of `markmap` instead of drawing directly on DOM. Is there an any way to get this?

**Comment by gera2ld** [comment]
This is not possible now because the size of each cell has to be calculated after it is mounted to document. It's hard to measure the sizes in other ways after supporting different styles, links, MathJax, etc.

What's your use case? How about getting the string by `svg.outerHTML`?

**Comment by dodok8** [comment]
I try to build VS Code extension change markdown into mindmap using Webview api provide by VS Code. Even I can run JS code in `webview.html` using `<script />`, however it can't access yarn or npm so it occurs error when load. I can't find a way to access DOM of webview in outside of `webview.html`. So I thought 'how about get a string data of mindmap and directly export in `webview.html`?'. That's the reason I wrote this question. 

Thanks for your kind answer. Have a nice day
