### ISSUE TITLE
MathJax not working

### ISSUE THREAD

**Issue by desperadoshi** [gera2ld/markmap-lib#9]
Markdown file as follows,

```
# Separation

## Backward-facing Step

- Snoi_2017AIAAJ_TurbulentSupersonicBackwardFacingStep
  - OpenFOAM LES using an equilibrium wall model with $y^+=20$, 2nd order scheme, BDF2 with CFL<0.5.
    Relatively good match with the experimental data.
    Also do POD.
    I do not think this is a good paper.
  - $y^+=20$
```

Using the command `markmap --no-open --enable-mathjax Separation_MindMap.md`, it gives the following output, resulting in no MathJax rendered.

![markmap](https://user-images.githubusercontent.com/9106886/79839507-2d5d6180-83e7-11ea-99d7-86ce0d7af281.jpg)

My markmap version is

```
$ markmap --version
0.6.0
```

**Comment by gera2ld** [comment]
Currently only `\(...\)` is supported, as in [the default options of MathJax](http://docs.mathjax.org/en/latest/options/input/tex.html#option-descriptions).

> the single dollar signs are not enabled by default because they are used too frequently in normal text, so if you want to use them for math delimiters, you must specify them explicitly.

Note that you need to escape the slash `\\` if you don't want to wrap it as inline code. Either way works:
- `` `\(y^+=20\)` ``
- `\\(y^+=20\\)`

I'll see if there is an easy way to pass in custom options in the future.

**Comment by desperadoshi** [comment]
> Currently only `\(...\)` is supported, as in [the default options of MathJax](http://docs.mathjax.org/en/latest/options/input/tex.html#option-descriptions).
> 
> > the single dollar signs are not enabled by default because they are used too frequently in normal text, so if you want to use them for math delimiters, you must specify them explicitly.
> 
> Note that you need to escape the slash `\\` if you don't want to wrap it as inline code. Either way works:
> 
> * `` `\(y^+=20\)` ``
> * `\\(y^+=20\\)`
> 
> I'll see if there is an easy way to pass in custom options in the future.

Now I know how to use it. I tried several style of writing, and the outputs of them are as follows,

```
  - \(y^+=20\)
  - \( y^+=20 \)
  - `\(y^+=20\)`
  - \\(y^+=20\\)
```

![mathjax](https://user-images.githubusercontent.com/9106886/79940628-de6e0580-8494-11ea-9db2-c9db3cf0b5d6.jpg)
